# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'email_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QScrollBar

import Receiving_end

class Ui_email_window(object):
    def setupUi(self, email_window):
        email_window.setObjectName("email_window")
        email_window.setWindowTitle( "Emails")
        email_window.resize(762, 600)
        email_window.setStyleSheet("background-color: rgb(229, 229, 229);")
        self.centralwidget = QtWidgets.QWidget(email_window)
        self.centralwidget.setObjectName("centralwidget")
        self.email_viewer = QtWidgets.QListWidget(self.centralwidget)
        self.email_viewer.setGeometry(QtCore.QRect(50, 120, 661, 401))

        #showing all the emails

        self.email_viewer.setObjectName("email_viewer")

        inbox_list=Receiving_end.recieving(self.email,self.password)
        inbox_text=Receiving_end.conversion_in_string(inbox_list)
        self.email_viewer.addItem(inbox_text)
        self.email_label = QtWidgets.QLabel(self.centralwidget)
        self.email_label.setGeometry(QtCore.QRect(260, 30, 231, 81))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.email_label.setFont(font)
        self.email_label.setTextFormat(QtCore.Qt.AutoText)
        self.email_label.setScaledContents(False)
        self.email_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.email_label.setObjectName("email_label")
        self.email_label.setText("Emails")

        #for scroll bars
        scroll_bar = QScrollBar()
        self.email_viewer.setVerticalScrollBar(scroll_bar)
        email_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(email_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 762, 26))
        self.menubar.setObjectName("menubar")
        email_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(email_window)
        self.statusbar.setObjectName("statusbar")
        email_window.setStatusBar(self.statusbar)

    def sent_window(self,a):
        self.email=a[0]
        self.password=a[1]



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    email_window = QtWidgets.QMainWindow()
    ui = Ui_email_window()
    ui.setupUi(email_window)
    email_window.show()
    sys.exit(app.exec_())
