# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from second_window import Ui_second_MainWindow



EMAIL= ''

PASSWORD = ''


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Login Window")
        MainWindow.resize(577, 396)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        #This is the main button
        self.pushButton = QtWidgets.QPushButton(self.centralwidget,clicked=lambda: self.open_window2(MainWindow))
        self.pushButton.setGeometry(QtCore.QRect(250, 250, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setText("enter")

        #main label
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(230, 10, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Cooper Black")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label.setText("LOG IN")


        #Email label
        self.BUTTON1 = QtWidgets.QLabel(self.centralwidget)
        self.BUTTON1.setGeometry(QtCore.QRect(250, 80, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.BUTTON1.setFont(font)
        self.BUTTON1.setText("EMAIL")


        self.BUTTON1.setObjectName("BUTTON1")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(240, 150, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)

        #label of password
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_3.setText("Password")

        #This is the password text field
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(210, 190, 141, 31))
        self.textEdit.setObjectName("textEdit")

        self.textEdit.setText("password")

        #This is the password text field
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(210, 110, 141, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_2.setText("gmail.com")
        MainWindow.setCentralWidget(self.centralwidget)


        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 577, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

    def open_window2(self,MainWindow):
        EMAIL = self.textEdit_2.toPlainText()
        PASSWORD = self.textEdit.toPlainText()
        print(EMAIL)
        print(PASSWORD)
        MainWindow.close()
        self.window=QtWidgets.QMainWindow()
        self.ui=Ui_second_MainWindow()
        self.ui.setpassword(EMAIL,PASSWORD)
        self.ui.setupUi(self.window)
        self.window.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
